version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./infrastructure/docker/Dockerfile
    ports:
      - 8999:9090
    volumes: 
      - type: bind
        source: ./queue.db
        target: /queue.db