version: '3.4'

services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    build:
      context: ../
      dockerfile: infrastructure/docker/Dockerfile
    env_file: ../.env
    restart: unless-stopped
